// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Mcj4RpQp_b2oVk1_LcHewKa8PHKAHk4',
    appId: '1:808280580439:web:d34d81ac35c0043f60de12',
    messagingSenderId: '808280580439',
    projectId: 'e-commerce-aadc3',
    authDomain: 'e-commerce-aadc3.firebaseapp.com',
    storageBucket: 'e-commerce-aadc3.appspot.com',
    measurementId: 'G-R9X86HELN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ0nR3mR-armYKwOYBegGgA37WJua_XkA',
    appId: '1:808280580439:android:0443cedcc38d129b60de12',
    messagingSenderId: '808280580439',
    projectId: 'e-commerce-aadc3',
    storageBucket: 'e-commerce-aadc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqTlvr_7AwmHUeE7O4w6wjWMMcF0V9Upw',
    appId: '1:808280580439:ios:c94d4ac359b2b6c860de12',
    messagingSenderId: '808280580439',
    projectId: 'e-commerce-aadc3',
    storageBucket: 'e-commerce-aadc3.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqTlvr_7AwmHUeE7O4w6wjWMMcF0V9Upw',
    appId: '1:808280580439:ios:c94d4ac359b2b6c860de12',
    messagingSenderId: '808280580439',
    projectId: 'e-commerce-aadc3',
    storageBucket: 'e-commerce-aadc3.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Mcj4RpQp_b2oVk1_LcHewKa8PHKAHk4',
    appId: '1:808280580439:web:129dc64287ce12b260de12',
    messagingSenderId: '808280580439',
    projectId: 'e-commerce-aadc3',
    authDomain: 'e-commerce-aadc3.firebaseapp.com',
    storageBucket: 'e-commerce-aadc3.appspot.com',
    measurementId: 'G-P58J5TN83E',
  );
}
